---
- name: Instalación de Munin (Monitoreo)
  apt: name={{ items }} state=present
  with_items:
    - munin-node
    - munin-plugins-extra
    - git
 - name: ensure config is latest
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    mode: 0644
  notify: restart munin-node
